add support for aws backend in external secrets
cloudkite-io/helm-standard-library pull request #42
Opened 2024-12-19 16:04 UTC by TeamoreA

2024-12-19 20:30 UTC, kirill-cloudkite approved these changes

2024-12-19 20:50 UTC, MuriukiPM requested changes
Can we get an example in [example.values.yaml](https://github.com/cloudkite-io/helm-standard-library/blob/main/standard-app/example.values.yaml) ?

2024-12-20 16:46 UTC, TeamoreA commented
> Can we get an example in [example.values.yaml](https://github.com/cloudkite-io/helm-standard-library/blob/main/standard-app/example.values.yaml) ?

Sure, I have added.

2024-12-20 17:17 UTC, MuriukiPM approved these changes

2024-12-20 17:19 UTC, merged